#!/bin/sh

: ${upstream:=origin}

REPO=`git config --get remote.$upstream.url`
MERGED=`git rev-parse $upstream/gh-pages^2`
CURRENT=`git rev-parse $upstream/2016`

git fetch $upstream

echo "upstream is $upstream"
echo "works on $REPO"
echo "$MERGED is last parent of $upstream/gh-pages"
echo "$CURRENT is current $upstream/2016"

if [[ $MERGED != $CURRENT ]]; then
  rm -rf dist
  git clone $REPO --depth 1 -b gh-pages dist
  ./node_modules/.bin/webpack
  cd dist
  git fetch --depth 1 $upstream 2016:2016
  git add -A .
  git reset --hard $(git commit-tree `git write-tree` -p `git rev-parse gh-pages` -p `git rev-parse 2016` -m "regen for `git rev-parse 2016`")
  git push $upstream gh-pages
  cd ..
else
  echo "up to date"
fi
